<?php

?>
<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-account"><?php echo Mage::helper('payperrentals')->__('Reservation') ?></h4>
	</div>
	<div class="grid np">
		<div class="hor-scroll">
			<table id="payperrentals-orders-table" class="data" cellspacing="0" width="100%">
				<col width="25%"/>
				<col/>
				<col width="25%"/>
				<col width="25%"/>
				<thead>
					<tr class="headings">
						<th><?php echo $this->__('SKU')?></th>
						<th><?php echo $this->__('Product Name')?></th>
						<th class="a-center"><?php echo $this->__('From')?></th>
						<th class="a-center"><?php echo $this->__('To')?></th>
					</tr>
				</thead>
				<tbody class="odd">

					<?php foreach($this->getCollection() as $item): ?>

					<tr class="border">
						<td><?php echo $this->getProductSKU($item->getProductId());//$item->getSku()?></td>
						<td><?php echo $this->getProductName($item->getProductId());;//$item->getProductName()?></td>
						<td class="a-right"><?php echo ITwebexperts_Payperrentals_Helper_Data::formatDbDate( $item->getStartDate(),false,false);?></td>
						<td class="a-right"><?php echo ITwebexperts_Payperrentals_Helper_Data::formatDbDate( $item->getEndDate(),false,false)?></td>
					</tr>
					<?php endforeach;?>
				</tbody>
			</table>
			<br/>
		</div>
	</div>
</div>
<div class="clear"></div>
